--회원가입
--이름, ID, PW, 전화, 이메일, 나이

--1. column level 방식
CREATE TABLE MEMBER(
	ID VARCHAR2(50) CONSTRAINT MEMBER_ID_PK PRIMARY KEY,
	PW VARCHAR2(50) CONSTRAINT MEMBER_PW_NN NOT NULL,
	NAME VARCHAR2(50),
	PHONE VARCHAR2(50) CONSTRAINT MEMBER_PH_U UNIQUE,
	EMAIL VARCHAR2(100) CONSTRAINT MEMBER_EMAIL_U UNIQUE,
	AGE NUMBER(3) CHECK (AGE BETWEEN 0 AND 150)
);

--2. table level 방식
CREATE TABLE MEMBER(
	ID VARCHAR2(50) ,
	PW VARCHAR2(50) ,
	NAME VARCHAR2(50),
	PHONE VARCHAR2(50) ,
	EMAIL VARCHAR2(100) ,
	AGE NUMBER(3),
	CONSTRAINT MEMBER_ID_PK PRIMARY KEY (ID),
	--안댐 CONSTRINT MEMBER_PW_NN NOT NULL (PW)
	CONSTRAINT MEMBER_PHONE_U UNIQUE (PHONE)
	);

--게시판 이름, 게시글 번호:제목:신뢰도:첨부img:등록날짜(신규)		닉네임:등록날짜
CREATE TABLE BOARD(
	NUM NUMBER CONSTRAINT BOARD_NUMBER_PK PRIMARY KEY,
	TITLE VARCHAR2(200),
	CONTENTS CLOB,
	WRITER VARCHAR2(50) CONSTRAINT BOARD_WR_FK REFERENCES MEMBER (ID),
	REGDATE DATE,
	HIT NUMBER

)

INSERT INTO BOARD 
VALUES(2, 'T1', 'C1', 'W1', SYSDATE, 0);

SELECT * FROM BOARD;

INSERT INTO MEMBER (ID, PW, NAME, PHONE, EMAIL, age)
VALUES ('W1', 'test', 'test', '', 'test@gmail.com',30);

SELECT * FROM MEMBER;

INSERT INTO MEMBER (ID, PW, NAME, PHONE, EMAIL, age)
VALUES ('test3', 'test', 'test', '1111', '',30);

SELECT  * FROM USER_CONSTRAINTS;

DELETE MEMBER WHERE ID = 'W1';
DELETE BOARD WHERE NUM=2;


DROP TABLE MEMBER;
DROP TABLE BOARD;