
--SELECT * FROM 상품들 P 
--	INNER JOIN
--	옵션 O
--	ON (P.상품번호 = O.상품번호)
--	INNER JOIN
--	댓글 C
--	ON (C.상품번호 = P. 상품번호)
--WHERE 상품번호=1
--
--SELECT * FROM 옵션  O WHERE 상품번호=1


--SEQ 널 것.
--CREATE TABLE MEMBER(
--	MEMBER_ID	VARCHAR2(100),
--	PASSWORD	VARCHAR2(100),
--	NAME		VARCHAR2(100),
--	PHONENUMBER	VARCHAR2(20),
--	EMAIL		VARCHAR2(100),
--	ADDRESS		VARCHAR2
--
--)

CREATE TABLE PRODUCT(
	PRODUCT_NUM 	NUMBER,
	PRODUCT_NAME	VARCHAR2(200),
	PRODUCT_DETAIL	CLOB,
	PRODUCT_JUMSU	NUMBER(2,1)
	
)

CREATE TABLE PRUDUCTOPTION(
	OPTION_NUM		NUMBER,
	PRODUCT_NUM		NUMBER,
	NAME			VARCHAR2(100),
	PRICE			NUMBER,
	STOCK			NUMBER
	
)

CREATE TABLE COMMENT_(
	COMMENT_NUM		NUMBER,
	PRODUCT_NUM		NUMBER,
	MEMBER_ID		VARCHAR2(100),
	JUMSU			NUMBER(2,1),
	DATEE			DATE,
	AUTHOR			VARCHAR2(100),
	COMMENT_BODY	VARCHAR2(4000)
);
ALTER TABLE PRODUCT ADD CONSTRAINT PK PRIMARY KEY (PRODUCT_NUM);
ALTER TABLE COMMENT_ ADD CONSTRAINT PRODUCT_NUM_FK FOREIGN KEY (PRODUCT_NUM)
REFERENCES PRODUCT (PRODUCT_NUM);
ALTER TABLE COMMENT_ ADD CONSTRAINT COMENT_MEMBER_ID_FK_ FOREIGN KEY (MEMBER_ID)
REFERENCES MEMBER (MEMBERID);
ALTER TABLE PRUDUCTOPTION ADD CONSTRAINT OPTION_NUM_PK PRIMARY KEY (OPTION_NUM);
ALTER TABLE PRUDUCTOPTION ADD CONSTRAINT PRUDUCTOPTION_PRODUCT_NUM_FK FOREIGN KEY (PRODUCT_NUM)
REFERENCES PRODUCT (PRODUCT_NUM);

SELECT * FROM USER_CONSTRAINTS;

SELECT * FROM PRODUCT p ;
SELECT * FROM "MEMBER" m ;
INSERT INTO MEMBER 
VALUES('TEST2','TEST','TEST','TEST','TEST','TEST');

RENAME MEMBER TO MEMBER_;

CREATE SEQUENCE SEQ01_SEQ;

INSERT INTO COMMENT_ 
VALUES (SEQ01_SEQ.NEXTVAL, 1, 'test'+TO_CHAR(SEQ01_SEQ.NEXTVAL, '999'),1,SYSDATE,'TEST','AA' )

COMMIT;



